config/routes.rb
Nomster::Application.routes.draw do

  devise_for :users
  root 'places#index'
  resources :places do
    resources :comments, :only => :create
    resources :pics, :only => :create
  end

  resources :users, :only => :show

  resources :places

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :place
	after_create :send_comment_email

	RATINGS = {
		'One Star' => '1_star',
		'Two Stars' => '2_stars',
		'Three Stars' => '3_stars',
		'Four Stars' => '4_stars',
		'Five Stars' => '5_stars'
	}

	def humanized_rating
		RATINGS.invert[self.rating]
	end

	def send_comment_email
		NotificationMailer.comment_added(self).deliver
	end
	# To test (all dev configuration commented out to not actually mail):
	# In rails console > Comment.last.send_comment_email

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	belongs_to :place

	mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :pics

	validates :name, :presence => true, length: { minimum: 3 }, uniqueness: { case_sensitive: false }
	validates :address, :presence => true
	validates :description, :presence => true

	geocoded_by :address # this might need to be done by a custom method
	after_validation :geocode


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@place = Place.find(params[:place_id])
		@place.comments.create(comment_params.merge(:user => current_user))
		redirect_to place_path(@place)
	end

	private

	def comment_params
		params.require(:comment).permit(:message, :rating)
	end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	def create
		@place = Place.find(params[:place_id])
		@place.pics.create(pic_params)
		redirect_to place_path(@place)
	end

	private

	def pic_params
		params.require(:pic).permit(:caption, :picture, :place_id)
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

	def index
		@places = Place.order("name").page(params[:page]).per(3)
	end

	def new
		@place = Place.new
	end

	def create
		@place = current_user.places.create(place_params)
		if @place.valid?
			redirect_to root_path
		else
			render :new, :status => :unprocessable_entity
		end
	end

	## I think this will be where I need to set a new method for Geocoder(?)
	def show
		@place = Place.find(params[:id])
		@comment = Comment.new
		@pic = Pic.new
	end

	def edit
		@place = Place.find(params[:id])

		if @place.user != current_user
			return render :text => 'Lacking Permissions', :status => :forbidden
		end
	end

	def update
		@place = Place.find(params[:id])
		if @place.user != current_user
			return render :text => 'Lacking Permissions', :status => :forbidden
		end

		@place.update_attributes(place_params)
		if @place.valid?
			redirect_to root_path
		else
			render :edit, :status => :unprocessable_entity
		end
	end

	def destroy
		@place = Place.find(params[:id])
		if @place.user != current_user
			return render :text => 'Lacking Permissions', :status => :forbidden
		end

		@place.destroy
		redirect_to root_path
	end

	private

	def place_params
		params.require(:place).permit(:name, :description, :address)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="initial-scale=1.0, width=device-width" />
</head>
<body>

  <!-- NAVBAR -->
  <nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'where it\'s @', root_path, :class => 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to new_place_path do %>
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            new place
          <% end %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'My Profile', user_path(current_user) %></li>
          <li><%= link_to 'Log out?', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Please log in', new_user_session_path %></li>
          <li><%= link_to 'Sign up!', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

<br />
<div class="col-xs-12 col-md-10 col-md-offset-1">
  <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>


<footer>
  <div class="footer col-xs-12 text-center">
    <br />
  	<h6>Sha-nae-nae &copy;2015</h6>
  </div>
</footer

</body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1>Edit the location details</h1>
	<%= simple_form_for @place do |f| %>
		<%= f.input :name %>
		<br />
		<%= f.input :address %>
		<br />
		<%= f.input :description %>
</div>
<div class="col-xs-10 col-xs-offset-1">
	<br />
		<%= f.submit 'Update', :class => 'btn btn-primary btn-lg text-right' %>
	<% end %>
</div>

app/views/places/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag 'slider1.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Seeking nightlife activity while in Baltimore?
      </div>
    </div>
    <div class="item">
      <%= image_tag 'slider2.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Exploring Philadelphia for the day?
      </div>
    </div>
    <div class="item">
      <%= image_tag 'slider3.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Looking for drinking & dancing in Indianapolis?
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<% @places.each do |place| %>
	<div class="booyah-box col-xs-10 col-xs-offset-1">
		<h1 class="location"><%= link_to place.name, place_path(place) %></h1>
		<i><%= place.address %></i>
		<br />
		<p class="about"><%= place.description %></p>
		<br />

		<% if place.user.present? %>
			<small><%= place.user.email %></small>
		<% end %>

		<% if place.comments.present? %>
			<div class="col-xs-12">
				<blockquote>
          <%= place.comments.last.message %>
					<% if place.comments.last.humanized_rating.present? %>
            <br />
					  <b><%= place.comments.last.humanized_rating %></b>
					<% end %>
					<span class="align"><small><%= place.comments.last.user.email %></small></span>
				</blockquote>
			</div>
		<% end %>

	</div>
<% end %>

<div class="pagination col-xs-12 text-center">
	<nav>
		<%= paginate @places, :window => 1 %>
	</nav>
</div>

app/views/places/new.html.erb
<div class="booyah-box heading col-xs-10 col-xs-offset-1">
	<h1>Add a Fave Place</h1>
</div>
<div class="col-xs-10 col-xs-offset-1 form">
	<%= simple_form_for @place do |f| %>
		<%= f.input :name %>
		<br />
		<%= f.input :address %>
		<br />
		<%= f.input :description, :placeholder => 'Is the food fantastic? The vibe vivacious? Let us know!' %>
		<br />
		<%= f.submit 'Add it!', :class => 'btn btn-primary btn-lg text-right' %>
	<% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1 class="location"><%= @place.name %></h1>
	<i><%= @place.address %></i>
	<br />
	<p class="about"><%= @place.description %></p>

<% if @place.latitude.present? && @place.longitude.present? %>
    <script>
			function initMap() {
			  var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

			  var map = new google.maps.Map(document.getElementById('map'), {
			    zoom: 12,
			    center: myLatLng
			  });

			  var marker = new google.maps.Marker({
			    position: myLatLng,
			    map: map,
			    title: 'Hello World!'
			  });
			}
    </script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?signed_in=true&callback=initMap">
		</script>
  	<div id="map"></div>
	<% end %>

	<br />

	<div class="pull-right">
		<% if current_user && current_user == @place.user %>
			<%= link_to 'Edit', edit_place_path(@place), :class => 'btn btn-primary' %>
			<%= link_to 'Remove', place_path(@place), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this?'}, :class => 'btn btn-danger' %>
		<% end %>
	</div>
</div>

<div class="clear"></div>

<!-- Comments Modal -->
<div class="modal fade" id="myCommentsModal" tabindex="-1" role="dialog" aria-labelledby="myCommentsModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myCommentsModalLabel">Contribute your comment</h4>
      </div>

	  	<%= simple_form_for @comment, :url => place_comments_path(@place) do |f| %>
	      <div class="modal-body">
						<%= f.input :message %>
						<br />
						<%= f.input :rating, :as => :select, :collection => Comment::RATINGS %>
		  	</div>
				<div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <%= f.submit "Add comment", :class => 'btn btn-primary' %>
	      </div>
			<% end %>

    </div>
  </div>
</div>

<div class="col-xs-10 col-xs-offset-1">
	<br />
	<div class="btn-group pull-right" role="group">
		<!-- Comments Button trigger modal -->
		<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myCommentsModal">
		  Add a comment?
		</button>
		<!-- Pics Button trigger modal -->
		<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myPicsModal">
		  Contribute a photo?
		</button>
	</div>
</div>

<div class="col-xs-10 col-xs-offset-1 border">
<h1 class="purple_heading">Comments</h1>
	<% if @place.comments.present? %>
		<% @place.comments.each do |comment| %>
				<blockquote>
					<%= comment.message %>
					<% if comment.humanized_rating.present? %>
					<br />
						<b><%= comment.humanized_rating %></b>
					<% end %>
					<span class="align"><small><%= comment.user.email %></small></span>
				</blockquote>
			<% end %>
	<% else %>
		<h4 class="col-xs-offset-1">No posted comments for this location</h4>
	<% end %>
</div>

<!-- Pics Modal -->
<div class="modal fade" id="myPicsModal" tabindex="-1" role="dialog" aria-labelledby="myPicsModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myPicsModalLabel">Upload a photo & add a caption</h4>
      </div>

	  	<%= simple_form_for @pic, :url => place_pics_path(@place) do |f| %>
	      <div class="modal-body">
						<%= f.input :picture %>
						<br />
						<%= f.input :caption %>
		  	</div>
				<div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <%= f.submit "Add image", :class => 'btn btn-primary' %>
	      </div>
			<% end %>

    </div>
  </div>
</div>

<div class="col-xs-10 col-xs-offset-1">
	<h1 class="purple_heading">Pics</h1>
	<% if @place.pics.present? %>
		<div >
			<% @place.pics.each do |pic| %>
					<%= image_tag pic.picture.medium, :class => 'img-responsive' %>
					<br />
					<%= pic.caption %>
			<% end %>
		</div>
	<% else %>
		<h4 class="col-xs-offset-1">No pictures posted for this location</h4>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<div class="col-xs-4">
		<%= image_tag 'avatar.png' %>
	</div>
	<div class="col-xs-8 text-right">
		<h1><%= @user.email %></h1>
		<h3>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
		<h4><%= @user.comments.count %> total comments</h4>
		<h4><%= @user.comments.where(:rating => '5_stars').count %> total 5-star reviews</h4>
	</div>
	<div class="clear"></div>
</div>

<div class="col-xs-10 col-xs-offset-1 border">
	<h1 class="purple_heading">My Comments</h1>
	<% if @user.comments.present? %>
		<% @user.comments.each do |comment| %>
		<h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
			<blockquote>
				<%= comment.message %>
				<br />
				<% if comment.humanized_rating.present? %>
					<b><%= comment.humanized_rating %></b>
				<% end %>
				<span class="align"><small><%= comment.user.email %></small><span>
			</blockquote>
		<% end %>
		<% else %>
			<h4>You haven't posted any comments yet</h4>
	<% end %>
</div>

<div class="col-xs-10 col-xs-offset-1">
	<h1 class="purple_heading">My Places</h1>
	<br/ >
	<% if @user.places.present? %>
		<% @user.places.each do |place| %>
			<div class="col-xs-12 booyah-box">
				<h1 class="location"><%= link_to place.name, place_path(place) %></h1>
				<i><%= place.address %></i>
				<br />
				<p class="about"><%= place.description %></p>
				<% if place.comments.present? %>
						<blockquote>
							<%= place.comments.last.message %>
							<br />
							<% if place.comments.last.humanized_rating.present? %>
								<b><%= place.comments.last.humanized_rating %></b>
							<% end %>
							<span class="align"><small><%= place.comments.last.user.email %></small></span>
						</blockquote>
				<% end %>
			</div>
		<% end %>
	<% else %>
				<h4>You didn't post any locations</h4>
	<% end %>
</div>